config/routes.rb
Outsidekick::Application.routes.draw do

  resources :early_users

  root 'early_users#new'

  ["terms", "privacy_policy", "contact_us", "about"].each do |page|
    get page => "pages##{page}", :as => page
  end
  
  post '/submit_contact' => 'mailer#deliver_contact_form'
  

  

end

app/models/early_user.rb
class EarlyUser < ActiveRecord::Base
  validates :email, :presence => true, :uniqueness => true, 
    :format => { :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/early_users_controller.rb
class EarlyUsersController < ApplicationController

  def new
    @early_user = EarlyUser.new 
  rescue 
  end

  def create
    @early_user = EarlyUser.new 
    if params["early_user"]
      @early_user.email = params["early_user"]["email"]
      @early_user.save!
    end
    redirect_to "/"
  rescue ActiveRecord::RecordInvalid => e
    #TODO show errors
    redirect_to "/"
  rescue => e
  end
end

app/controllers/mailer_controller.rb
class MailerController < ActionController::Base
  def deliver_contact_form
    address = params["contact_email"]
    details = params["contact_detail"]
    subject = params["subject"] || ""
    ContactUsMailer.mail_outsidekick(address, subject, details).deliver
    redirect_to contact_us_url, notice: "Watch it, mister!"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def privacy_policy
  end

  def terms
  end

  def contact_us
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/early_users_helper.rb
module EarlyUsersHelper
end

app/views/application/_navbar.html.haml
.navbar
  .navbar-inner
    .container
      #logo
        =link_to(image_tag("outsidekick_logo_green.png"), "/")
      %ul.nav
        %li= link_to "Home", "/"
        %li= link_to "About", "/about" 
        %li= link_to "Contact", "/contact_us"
        %li= link_to "Privacy Policy", "/privacy_policy"

app/views/early_users/_about_outsidekick.html.haml
.about-wrapper
  %h3
    %span Your 
    %span.outside Outside 
    %span.sidekick SideKick
  .details
    %p
      Any where you go. Whenever you want. OutsideKick sitting in our hands and in the clouds, can be with you and locate you. In case of emergency It'll contact your requested Emergency Contacts. 
    %p Be outside with a peace of mind for your you and your loved ones. 

app/views/early_users/_form.html.haml
.welcome-box
  .welcome-message
    %p.head Welcome!
    %p Be the first to know about us!
  = form_for @early_user do |f|
    - if @early_user.errors.any?
      #error_explanation
        %h2= "#{pluralize(@early_user.errors.count, "error")} prohibited this early_user from being saved:"
        %ul
          - @early_user.errors.full_messages.each do |msg|
            %li= msg

    .field
      = f.text_field :email, placeholder: 'Your email'
    .actions
      = f.button 'Submit', type: 'submit', class: 'btn btn-warning btn-large'

app/views/early_users/_home_page_sections.html.haml
-#%section.video
  -#= render partial: 'welcome_video' 
-#%section.photo
  -#= render partial: 'third_photo'

app/views/early_users/_third_photo.html.haml
.third-photo

app/views/early_users/_welcome_video.html.haml
.video_wrapper
  %iframe(src="//player.vimeo.com/video/47355798" width="750" height="421" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen)

app/views/early_users/create.html.haml
.hero-unit
  = render partial: "form"
= render partial: 'home_page_sections'

app/views/early_users/edit.html.haml
%h1 Editing early_user

= render 'form'

= link_to 'Show', @early_user
\|
= link_to 'Back', early_users_path

app/views/early_users/new.html.haml
.hero-unit
  = render partial: "form"
= render partial: 'home_page_sections'

app/views/early_users/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @early_user.email

= link_to 'Edit', edit_early_user_path(@early_user)
\|
= link_to 'Back', early_users_path

app/views/layouts/application.html.haml
%html
  %head
    %title Outsidekick | Personal Outside Safety
    %meta{ :charset => "utf-8" }
    %meta{ :name => "description", :content => "TODO1 fill in from meta.yml" }
    %meta{ :name => "keywords", :content => "TODO1 fill in from meta.yml" }
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    %link{:href => "favicon.ico", :rel => "shortcut icon"}
  %body#dark-background
    .container
      #outer_layout
        #wrapper
          #inner_wrapper
            = render partial: 'navbar'
            = yield

app/views/pages/_follow_twitter.html.haml
<a href="https://twitter.com/MyOutSideKick" class="twitter-follow-button" data-show-count="false">Follow @MyOutSideKick</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

app/views/pages/about.html.haml
#about-page-wrapper.page-body
  %h3 Get outdoors, with a peace of mind.
  %br
  %h4 About OutSideKick
  .details
    %p
      OutSideKick is Founded in San Francisco, California in 2013. It is here to help you track yourself while doing outdoor activities. You can send your location to your emergency contacts in case of  
  %br
  %h4 About The Team
  .details
    %p
      We are a first class team of engineers and outdoor enthusiasts. We love spending our time in the peacefulness of nature, the only catch is, in case of emergency it's hard for your loved ones to find you. Our mission is to let you have fun and let you and your loved ones relax while you are outdoors. We would love to hear your feedbacks and suggestions.
  = render 'follow_twitter'
  %br
  %h4.you You
  .details
    %p
      Are you an outdoor enthusiasts? Are you concern about personal safety? 
      = link_to "Sign up", root_path
      with us to be one of the first people who get to use OutSideKick. 
      = link_to "Contact Us", contact_us_path
      and let us know what you like to see.

app/views/pages/contact_us.html.haml
#contact-us-page-wrapper.page-body
  %h3 Contact Us
  %br
  = form_tag(submit_contact_path,  :method=>'post') do 
    %p
      = label_tag(:contact_detail, "Your Email")
    %p
      = email_field_tag(:contact_email, nil, :autocomplete => true) 
    %p
      = label_tag(:contact_detail, "Details")
    %p 
      = text_area_tag(:contact_detail,:"", :size=> "66x8")
    %p
      = submit_tag("Submit", :class => "btn btn-warning", :disabled => false)
      
      
      
      

app/views/pages/privacy_policy.html.haml
#privacy-policy-page-wrapper.page-body
  %h3 Privacy Policy
  %p
    Protecting your private information is our priority. This Statement of Privacy applies to the www.outsidekick.com and OutSideKick, Inc.
  %p We don't collect any information from you besides what you send us in your email. OutSidKick is a work in progress, once we create the app and you can install it, we will create another Privacy Policy, and let you know about it.
  %br
  %h4 Use of Information
  %p
    OutSideKick does not sell, rent or lease its customer lists or their information to third parties.
  %br
  %h4 Opt-Out & Unsubscribe
  %p
    We respect your privacy and give you an opportunity to opt-out of receiving announcements of certain information. Users may opt-out of receiving any or all communications from Darby Smart by 
    = link_to "Contacting us", contact_us_path
  %br
  %h4 Effective Date
  %p This Privacy Policy is effective and was last updated on Oct 21, 2013.

app/views/pages/terms.html.erb
<!DOCTYPE html>
<html dir='<%= t(:direction_preference) %>' lang="<%= I18n.locale %>" class="<%= t(:direction_preference) %>">
  <head>
<title>Terms &amp; Conditions</title>
</head>

<body>
<div id="pageContent">


<h2>
	Web Site Terms and Conditions of Use
</h2>

<h3>
	1. Terms
</h3>

<p>
	By accessing this web site, you are agreeing to be bound by these 
	web site Terms and Conditions of Use, all applicable laws and regulations, 
	and agree that you are responsible for compliance with any applicable local 
	laws. If you do not agree with any of these terms, you are prohibited from 
	using or accessing this site. The materials contained in this web site are 
	protected by applicable copyright and trade mark law.
</p>

<h3>
	2. Use License
</h3>

<ol type="a">
	<li>
		Permission is granted to temporarily download one copy of the materials 
		(information or software) on Likes Me Likes Me Not's web site for personal, 
		non-commercial transitory viewing only. This is the grant of a license, 
		not a transfer of title, and under this license you may not:
		
		<ol type="i">
			<li>modify or copy the materials;</li>
			<li>use the materials for any commercial purpose, or for any public display (commercial or non-commercial);</li>
			<li>attempt to decompile or reverse engineer any software contained on Likes Me Likes Me Not's web site;</li>
			<li>remove any copyright or other proprietary notations from the materials; or</li>
			<li>transfer the materials to another person or "mirror" the materials on any other server.</li>
		</ol>
	</li>
	<li>
		This license shall automatically terminate if you violate any of these restrictions and may be terminated by Likes Me Likes Me Not at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.
	</li>
</ol>

<h3>
	3. Disclaimer
</h3>

<ol type="a">
	<li>
		The materials on Likes Me Likes Me Not's web site are provided "as is". Likes Me Likes Me Not makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, Likes Me Likes Me Not does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its Internet web site or otherwise relating to such materials or on any sites linked to this site.
	</li>
</ol>

<h3>
	4. Limitations
</h3>

<p>
	In no event shall Likes Me Likes Me Not or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption,) arising out of the use or inability to use the materials on Likes Me Likes Me Not's Internet site, even if Likes Me Likes Me Not or a Likes Me Likes Me Not authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.
</p>
			
<h3>
	5. Revisions and Errata
</h3>

<p>
	The materials appearing on Likes Me Likes Me Not's web site could include technical, typographical, or photographic errors. Likes Me Likes Me Not does not warrant that any of the materials on its web site are accurate, complete, or current. Likes Me Likes Me Not may make changes to the materials contained on its web site at any time without notice. Likes Me Likes Me Not does not, however, make any commitment to update the materials.
</p>

<h3>
	6. Links
</h3>

<p>
	Likes Me Likes Me Not has not reviewed all of the sites linked to its Internet web site and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by Likes Me Likes Me Not of the site. Use of any such linked web site is at the user's own risk.
</p>

<h3>
	7. Site Terms of Use Modifications
</h3>

<p>
	Likes Me Likes Me Not may revise these terms of use for its web site at any time without notice. By using this web site you are agreeing to be bound by the then current version of these Terms and Conditions of Use.
</p>

<h3>
	8. Governing Law
</h3>

<p>
	Any claim relating to Likes Me Likes Me Not's web site shall be governed by the laws of the State of California without regard to its conflict of law provisions.
</p>

<p>
	General Terms and Conditions applicable to Use of a Web Site.
</p>



<h2>
	Privacy Policy
</h2>

<p>
	Your privacy is very important to us. Accordingly, we have developed this Policy in order for you to understand how we collect, use, communicate and disclose and make use of personal information. The following outlines our privacy policy.
</p>

<ul>
	<li>
		Before or at the time of collecting personal information, we will identify the purposes for which information is being collected.
	</li>
	<li>
		We will collect and use of personal information solely with the objective of fulfilling those purposes specified by us and for other compatible purposes, unless we obtain the consent of the individual concerned or as required by law.		
	</li>
	<li>
		We will only retain personal information as long as necessary for the fulfillment of those purposes. 
	</li>
	<li>
		We will collect personal information by lawful and fair means and, where appropriate, with the knowledge or consent of the individual concerned. 
	</li>
	<li>
		Personal data should be relevant to the purposes for which it is to be used, and, to the extent necessary for those purposes, should be accurate, complete, and up-to-date. 
	</li>
	<li>
		We will protect personal information by reasonable security safeguards against loss or theft, as well as unauthorized access, disclosure, copying, use or modification.
	</li>
	<li>
		We will make readily available to customers information about our policies and practices relating to the management of personal information. 
	</li>
</ul>

<p>
	We are committed to conducting our business in accordance with these principles in order to ensure that the confidentiality of personal information is protected and maintained. 
</p>	
<div>
</body>
</html>
	